apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app.kubernetes.io/name: hello-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-service
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
