apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Namespace }}
data:
  ALGORITHM: {{ .Values.config.algorithm | quote }}
  ACCESS_TOKEN_EXPIRY: {{ .Values.config.accessTokenExpiry | quote }}
  REFRESH_TOKEN_EXPIRY: {{ .Values.config.refreshTokenExpiry | quote }}
  WINDOWS_SCREEN: {{ .Values.config.windowsScreen | quote }}
  ACCESS_COUNTER: {{ .Values.config.accessCounter | quote }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  ADMIN_EMAIL: {{ .Values.config.adminEmail | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDB | quote }}